node("master") {
    def build_file = 'Fonsview.APIGW_R1.0.0_743.tar.gz'
    def build_version = '743'
    def build_file_path = '"/home/monkey/it-fs/Upload/SS Department/monkey/mongodb"'

    stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'http://github.com/kikiyou/docker-test'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      sh "ls -l"
      sh "wget -q http://monkey.rhel.cc:8000/Fonsview.APIGW_R1.0.0_743.tar.gz "
   }

    docker.withRegistry('http://monkey.rhel.cc', 'docker-registry') {
    
        stage "build"
        def app = docker.build("library/apigw:latest","--file apigw/Dockerfile --tag library/apigw:${build_version} .")

        stage "publish"
        app.push 'latest'
        app.push "${build_version}"
    }
}
