import groovy.util.ConfigObject
import groovy.util.ConfigSlurper

@NonCPS
def configParse(file) {
    // new groovy.json.JsonSlurperClassic().parseText(json)
    def cc = new File(file).toURL()
    println "${cc}"
    def config = new groovy.util.ConfigSlurper().parse(cc)
}

node("master") {
    git 'http://github.com/kikiyou/docker-test'
    // def config = new ConfigSlurper().parse(new File("/tmp/config.groovy").toURL())
    def config = configParse('/tmp/config.groovy')

    def build_file = config.mongodb.build_file
    def build_version = config.mongodb.build_version
    def build_file_path = config.mongodb.build_file_path
    config = null
    sh "pwd"
    sh "ls -l"
    
    file = "${WORKSPACE}/config.groovy"
    println "---${file}---"
    stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository

      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      sh "ls -l"
      sh "wget -q http://monkey.rhel.cc:8000/Fonsview.APIGW_R1.0.0_743.tar.gz "
   }

    docker.withRegistry('http://monkey.rhel.cc', 'docker-registry') {
    
        stage "build"
        def app = docker.build("library/apigw:latest","--file apigw/Dockerfile --tag library/apigw:${build_version} .")

        stage "publish"
        app.push 'latest'
        app.push "${build_version}"
    }
}
